export const ROUTES = {
  TAB_NAVIGATION: 'TAB_NAVIGATION',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  LOADING_SCREEN: 'LOADING_SCREEN',
};
export const TAB_NAVIGATION = {
  HOME: 'HOME',
  CREATE: 'CREATE',
  SEARCH: 'SEARCH',
  PROFILE: 'PROFILE',
  MESSAGE: 'MESSAGE',
};

export const HOME_NAVIGATION = {
  NEW_FEED: 'NEWS_FEED',
  POST: 'POST',
  CHANNEL: 'CHANNEL',
};

export const PROFILE_NAVIGATION = {};
