export const ROUTES = {
  TAB_NAVIGATION: 'TAB_NAVIGATION',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  LOADING_SCREEN: 'LOADING_SCREEN',
};
export const TAB_NAVIGATION = {
  HOME: 'HOME',
  CREATE: 'CREATE',
  SEARCH: 'SEARCH',
  PROFILE: 'PROFILE',
  MESSAGE: 'MESSAGE',
};

export const HOME_NAVIGATION = {
  NEW_FEED: 'NEWS_FEED',
  POST: 'POST',
  CHANNEL: 'CHANNEL',
};

export const CHANNEL_LIST_NAVIGATION = {
  CHANNEL_LIST: 'CHANNEL_LIST',
  CHANNEL: 'CHANNEL',
  POST: 'POST'
}

export const PROFILE_NAVIGATION = {
  PROFILE: 'PROFILE',
  CREATE_CHANNEL: 'CREATE_CHANNEL',
  MY_POST: 'MY_POST'
};

export const SEARCH_NAVIGATION = {
  SEARCH: 'SEARCH',
};

export const CREATE_NAVIGATION = {
  CREATE: 'CREATE',
};

export const MESSAGE_NAVIGATION = {
  MESSAGE: 'MESSAGE',
  MESSAGE_BOX: 'MESSAGE_BOX'
};
